language: java
sudo: false
script: mvn clean verify
jdk:
  - oraclejdk8
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
      recipients:
      - olsen.oddbjorn@gmail.com
      on_success: never
      on_failure: always
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  local_dir: target/sentiment-1.0-SNAPSHOT/